version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
    - esdata:/usr/share/elasticsearch/data
    networks:
      tap:
        ipv4_address: 10.0.100.51

      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    environment:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      tap:
        ipv4_address: 10.0.100.52


volumes:
  esdata:
    driver: local

networks:
  tap:
    external: true